### ISSUE TITLE
Windows couldn't find libusbK.dll

### ISSUE THREAD

**Issue by fantoro** [eliboa/TegraRcmGUI#1]
![image](https://user-images.githubusercontent.com/20504699/40130785-5d7beade-5938-11e8-8124-82aa8bc805b9.png)
![image](https://user-images.githubusercontent.com/20504699/40130803-67ffb058-5938-11e8-81f7-47f51df0d0e8.png)

**Comment by eliboa** [comment]
Hi. Were you asked to install APX driver when you launched the app ? And did you install it ?
If you did there must be a problem with embeded driver, try to install libusbk driver for APX device with [Zadig](https://zadig.akeo.ie/)

**Comment by Real96** [comment]
I'm having the same problem. When i started the app, i wasn't asked to install anything. I installed the driver with both apx_driver folder provided in your rar and with Zadig. I'm getting the same error window of @fantoro

**Comment by eliboa** [comment]
Thank you Real96. I removed some amd64 related files from the APX provided driver (1.3). I'll look into it tonight, maybe I removed too many files... In the meantime, those having problems with libusbK dll can try Real96 solution.

@fantoro & @Real96, are you running the app on x86 or x64 system?

**Comment by Real96** [comment]
I'm on x64 system, W10

**Comment by eliboa** [comment]
Already have it ;-) Can I ask you to test the app after replacing you libusbK.dll by [this one](https://drive.google.com/open?id=1kKzPsbY-O-rf84I4MEef-KtX3Au1qNve) please ? Thank you

**Comment by Real96** [comment]
Ok, give me a sec :)

**Comment by Real96** [comment]
It worked perfectly with your file. Same way of the replaced file :) No error, could start the homebrew without any problems

**Comment by eliboa** [comment]
Cool ! I thank you and appreciate your help. I'm gonna publish a new release after work, with the right x64 files. Hopefully this will solve the problem.

**Comment by Real96** [comment]
I appreciate you work a lot! Thanks a lot and kt was a pleasure to help you :)

**Comment by fantoro** [comment]
I'm on x64 and it didn't ask me to install anything I just launched it. But as I see a fix was found.

**Comment by eliboa** [comment]
I updated [release 1.3.0](https://github.com/eliboa/TegraRcmGUI/releases/tag/1.3.0). The problem should be solved now.
Thank you both.
