### ISSUE TITLE
Starting Minimized does not make it Minimize to Tray

### ISSUE THREAD

**Issue by Kupie** [eliboa/TegraRcmGUI#13]
**Prerequesites:**

- Application started via a Shortcut (.lnk in Windows)
- Shortcut settings has it set to start "minimized" (like so: https://i.imgur.com/qsfAW34.png)
- Application set to "minimize to tray" in its settings Tab

**Expected behavior:**
Starting the app will start it minimized to tray

**Actual behavior:**
Starting the app will start it simply minimized, not to tray

**Environment:**
TegraRCMGUI v2.2, Windows 10 x64

**Comment by eliboa** [comment]
Thank youv ery much for reporting this (and providing useful details). I'll look into it (when back from holiday 😄). It's a strange behavior though because the app should always display a system tray icon. The option "minimize to tray" is actually mislabeled since the only thing this option does is to remove the app from taskbar and task switcher.

**Comment by eliboa** [comment]
Sorry, I did not have time to fix this bug yet.
In the meantime you should try to change the target for your shortcut, like that : "C:\switchhacking\TegraRcmGUI\TegraRcmGUI.exe /autostart" (using [TegraRcmGUI_v2.4](https://github.com/eliboa/TegraRcmGUI/releases/tag/2.4)).
/autostart argument should minimize the app to tray after start-up

**Comment by Kupie** [comment]
Nice! If there's a way to start it minimized to tray, then the original bug
really doesn't need fixing.

Thanks for all your hard work!

**Comment by jlduncan0** [comment]
I am still having this issue; however, I am launching the application from a pinned Taskbar shortcut/quick launch. 

After closing the GUI, I have found that the connection to the selected Nord server continues to remain uninterrupted; when the GUI is relaunched, the connection remains active using the same server. That said, I have never been able to see the "white Nord icon" appear in tray.

Thanks in advance for any insights you might have!
