### ISSUE TITLE
No RCM after injection

### ISSUE THREAD

**Issue by Annihilator708** [eliboa/TegraRcmGUI#14]
Happens with installed version. Driver is installed.
After clicking inject payload the switch turns on. (sx os payload).
Gui is telling me payload was successful.
me happy to start using UMS Tool.
Me totally wrong, NO RCM: Waiting for device in RCM mode.
After the logo of sx os disappeared this happend. Then the firmware boots.

Edit: My platform is windows 10 x64

**Comment by eliboa** [comment]
You can't use both SX OS payload (or any other payload) and UMS tool at the same time.
Simply power on your Switch in RCM mode (RCM OK), then click on UMS Tool button. Do your stuff, then power off the Switch. After that inject the payload you want to use (RCM Mode > Injection).

**Comment by eliboa** [comment]
Sorry but this has nothing to do with TegraRcmGUI so this will be my last comment.

You don't need the dongle to boot in RCM mode even if you have AutoRCM activated. Just use a USB cable and that's it. As I told you in my previous comment, you can't use both SX OS payload and UMS Tool at the same time....
1 - Connect your Switch to your PC (USB cable), if autoRCM is activated the GUI will display "RCM OK" (otherwise use the JIG and press POWER + VOL UP buttons)
2 - Click on UMS Tool button

**Comment by Annihilator708** [comment]
Tried both ways, ... I don't know how I'm able to prove this to you ¯\_(ツ)_/¯
Good luck with the software

**Comment by Annihilator708** [comment]
I figured it out thanks to discord support, here please take my star

**Comment by Melzera** [comment]
Hi, i´m having the same issue. After I updated the sx os and the firmware. My payload injects, the switch turns on the sx os screen and then it gets all black, and makes the noise of the usb beeing desconnected even thoug it´s still plugged in. Can anyone help? Thanks.

**Comment by eliboa** [comment]
This is not related to TegraRcmGUI.
If you can see SX OS screen after injecting payload, it means TegraRcmGUI has done its job.

**Comment by xate13** [comment]
> Happens with installed version. Driver is installed.
> After clicking inject payload the switch turns on. (sx os payload).
> Gui is telling me payload was successful.
> me happy to start using UMS Tool.
> Me totally wrong, NO RCM: Waiting for device in RCM mode.
> After the logo of sx os disappeared this happend. Then the firmware boots.
> 
> Edit: My platform is windows 10 x64

Can you please tell me how you were able to fix this issue. I am currently having the same problem

**Comment by eliboa** [comment]
Why would you want to use SX OS and UMS tool at the same time ? It's either one or the other.
Again, this is not an issue.

**Comment by 0x78f1935** [comment]
Your payload is prob corrupt, TegraRcmGUI is just a tool to serve the payload. So if your payload is corrupted you might end up with the kind of issues described above. I would like to recommend to read more up-to-date posts and do some research first. Also in the 2 years a lot has been changed. Keep that in mind aswell.
