### ISSUE TITLE
App freezes when injecting payload

### ISSUE THREAD

**Issue by tccolin70** [eliboa/TegraRcmGUI#15]
App goes unresponsive every time i try to inject the hekate payload, or any payload

using windows 10 64bit on an intel i5-3320M laptop

**Comment by tccolin70** [comment]
nevermind, it just took 15 minutes to inject the payload.

**Comment by eliboa** [comment]
It shouldn't take 15min (2/3 sec max). Weird...

**Comment by tccolin70** [comment]
after even more payload injections, hekate now gets injected perfectly fine in less than 5 seconds. though other payloads still take longer than that
