### ISSUE TITLE
USB device not recognized issues

### ISSUE THREAD

**Issue by falbjm** [eliboa/TegraRcmGUI#17]
Hi,
I had a problem. I can't connect my switch into my computer because it's not detected in TegraRcmGUI and shows a notification that "USB device not recognized." I had used before to inject my switch and successful with the same computer. After three days, my computer cant recognized my switch. I tried another USB port, and another computer still cants connect. Please help me. Thank you before

**Comment by eliboa** [comment]
Not related to TegraRcmGUI.
