### ISSUE TITLE
App always ask to install drivers

### ISSUE THREAD

**Issue by Real96** [eliboa/TegraRcmGUI#2]
Everytime i open the app, it asks to install APX drivers also if it was installed a second before xD If you click "Cancel", the app starts correctly anyway

**Comment by eliboa** [comment]
arfff, I tested it yesterday and it worked fine. I'll look into it.
Thank you for your feeback, again :D

**Comment by eliboa** [comment]
Real96, I think I found the problem. Would you mind testing the app after replacing your "TegraRcmGUI.exe" file by [this one](https://drive.google.com/open?id=1pnxxOhR_LdspstTxWdLXIyz6yGqkLz3Y) ?  Thank you


Another test you can do to help (only if you don't mind 👍) : 
- Manually delete C:\Windows\System32\libusbK.dll & C:\Windows\SysWOW64\libusbK.dll 
- Uninstall the libusbK driver package  (Start > Uninstall program) 
- Unistall APX device in "Device manager" (Switch has to be plugged in RCM mode) -- not sure this step is needed
Then you can test TegraRcmGUI again, with full driver installation.
Thx

**Comment by Real96** [comment]
Ok, it works. I tryed launching it a second time and it didn't ask me to install the drivers again. But i noticed that after opening the app the first time, the drivers installation window appear but at the same time also the app start. Is it normal?

**Comment by eliboa** [comment]
**Awesome** 👍  Yes, the thing with both apps launching at the same time is normal. Actually TegraRcmGUI is launching driver install but I think opening the main window before the prompt is a more understandable way of doing things (new idea for next release ;-)). Anyway, another bug fixed, thanks to you. 
[TegraRcmGUI 1.3 updated](https://github.com/eliboa/TegraRcmGUI/releases/tag/1.3.0)

**Comment by ada155** [comment]
hello everyone, i am having an issue with the Tegra RCM Gui 2.5 version, when  i firstly installed it on my pc it worked but now  it shows me that USB driver is K.O and inject payload button is grayed out. What can i do?
