### ISSUE TITLE
TegraRCM GUI Error code RC=-2

### ISSUE THREAD

**Issue by jayymonroe96** [eliboa/TegraRcmGUI#20]
I've been using the gui for a couple months now without issues, but for some reason now I keep getting error code RC=-2, I've tried resetting my pc, force closing all instances of the gui, and rebooting the switch into rcm mode multiple times, but nothing so far has worked.

**Comment by LumiaJ** [comment]
I think your computer is 32-bit system.

**Comment by jayymonroe96** [comment]
Thanka for the response, but may, my system is always 64 bit, turns out the switch was semi bricked

**Comment by eliboa** [comment]
This return code is related to TegraRcmSmash. Please use the CLI program to get more info about this error.
