### ISSUE TITLE
Error Code =-7 on v2.4 and =-8 on v2.1

### ISSUE THREAD

**Issue by Viper936** [eliboa/TegraRcmGUI#23]
This happens if I hold the buttons to get into rcm. If I just press them, it'll look like it's starting to inject, then stop responding. Once, I let it sit for about 20 mins and it never came back up.

**Comment by eliboa** [comment]
This error is returned by [TegraRcmSmash](https://github.com/rajkosto/TegraRcmSmash), not by TegraRcmGUI.
According to [Smasher.cpp](https://github.com/rajkosto/TegraRcmSmash/blob/master/Smasher.cpp), RC -7 or -8 means either "Win32 error %d happened trying to write payload buffer to RCM" or "Was only able to upload %d out of %d bytes of payload buffer".

To be certain the problem occurs only with TegraRcmSmash.exe, simply drag and drop a payload to TegraRcmSmash.exe while your console is plugged in RCM mode. If the error occurs again, then TegraRcmGUI is not at issue here (therefore you might get help by [opening an issue on TegraRcmSmash repo](https://github.com/rajkosto/TegraRcmSmash/issues))

**Comment by eliboa** [comment]
By the way, you should upgrade to the [latest version of TegraRcmGUI](https://github.com/eliboa/TegraRcmGUI/releases) which is more verbose than previous version (TegraRcmSmash stdout is now displayed by the GUI)

**Comment by Viper936** [comment]
Alright, I'll head over there. By running it thru TegraRCMSmash, it had gotten a step further and said it had initialized the USB and that it was injecting, but did nothing. Although it didn't stop responding.
