### ISSUE TITLE
Please include new biskeydumpv9_usb.bin

### ISSUE THREAD

**Issue by RussKay** [eliboa/TegraRcmGUI#27]
Please include the new biskeydumpv9_usb.bin. I see that it's the same size as the compressed size of biskeydumpv9.bin, so I'm not sure if it's a special build, but I'm assuming copy/past/renaming won't work. If it does, then please ignore. Otherwise, please update to v9 to support 8.1.0's boot0/1. Thanks!

**Comment by eliboa** [comment]
Thank you. Yes, biskeydump_usb.bin is a modified build of biskeydump that switch back to RCM mode right after dumping the keys. Copy/paste the payload from rajkosto's website may work but you'll need to reboot to RCM manually.
I'll update my custom payload when I'll find some time.

**Comment by eliboa** [comment]
biskeydump v9 is available in latest release
ce2d05edd4841f2ebbd9b070630fedc9ad8ec43a

**Comment by RussKay** [comment]
Thank you so much! ^_^
