### ISSUE TITLE
TegraRCMGUI stops responding when attempting to inject payload.

### ISSUE THREAD

**Issue by RandomBagel** [eliboa/TegraRcmGUI#28]
TegraRCMGUI stops responding when "Invoking TegraRCMSmash.exe with args : (somthing I cant see becasue it went off screen)"

TegraSmash seems to freeze up when injecting payloads as well, with "Opened USB Device path" stuck on the screen...

Any help? I have no clue if im patched or not, in fact thats what im trying to figure out, but biskeydump isnt working...

**Comment by eliboa** [comment]
TegraRcmGUI freezes when TegraRcmSmash.exe is not responding. Drag and drop the payload you want to push to the TegraRcmSmash.exe file (while on Windows Explorer), then you'll be able de get the std output from the command line program.

**Comment by RandomBagel** [comment]
I have tried that, but it gets stuck on "Opened USB path (bunch of numbers and letters)"
Still don't know if I'm patched or not, would really like to see if I am.

**Comment by eliboa** [comment]
This is not related to TegraRcmGUI. Make sure that your USB cable allows data transfer.

**Comment by Ari3lo1** [comment]
Doesn't seem to work for me either. Last message I get is uploading payload, then sizes listed in brackets and that's all it does. Any ideas? Tried 5 different cables in 2 different computers.

**Comment by murasio** [comment]
hay I have a problem my nintendo switch I have updated to 9.1.0 and now I want to have hacked I have all the TegraRcmGUI opened everything installed me device word as switch apx detected when I inject a file then go for payload press then befriest the program of TegraRcmGUI and then it says TegraRcmSmash invonking args what should I do now I have all looked to see if my switch is patch and he is not patch you can also nintendo switch that is not patched hack my serial number XKJ40012015616

**Comment by murasio** [comment]
![8wxp](https://user-images.githubusercontent.com/41643587/72673268-3b0dee80-3a68-11ea-8fe3-ac04a7f18719.jpg)

**Comment by colking** [comment]
I'm getting the same problem...

**Comment by ColBalls78292** [comment]
I tried injecting the payload again and it worked! Not sure why it didn't work the first time.

**Comment by murasio** [comment]
me nintendo switch is on firmware 9.1.0 and me serial is xkj4 can i hack me switch all times when i pay load it freeze

**Comment by murasio** [comment]
what i can do can i hack me switch or not
whay users need micro sd card is it to the payload wil send to micro sd card from pc to switch

**Comment by RobedSnake7** [comment]
I found a solution, use USB 3.0. Don't know why but it solved it for me.
