### ISSUE TITLE
favorites.conf not loaded

### ISSUE THREAD

**Issue by capitaineflam25** [eliboa/TegraRcmGUI#3]
Hi,

**favorites.conf** is well written in TegraRCMGUI folder but not loaded when closing it and opening it again.
Loading is implemented or is it a bug i'm facing ?
(I don't know if it is a big deal but duplicates can be created in **favorites.conf**)

PS: thanks for this great UI !

**Comment by eliboa** [comment]
Hi,
Thank you for reporting issue 👍 

favorites.conf should be loaded in the app when opening it (this is a bug) but yes, you can create duplicates (this should be fixed soon).
Please, can you download this executable => https://drive.google.com/open?id=18Ca-XU-t-JqXs5JJ8a0Vp-z2w1ms0oV9 and copy it in TergraRcmGUI folder (portable version) ? 

This version writes logs in output_log.txt. Can try this version to add new favorites & restart app. Once done, please send me the output (here or eliboa@gmail.com). 

Thank you for your help

**Comment by capitaineflam25** [comment]
Thanks for your answer.

Here is the log : `05:09:33 : Reading favorites.conf
05:09:33 : O:\Téléchargements\Nintendo Switch\SwitchHack\TegraRcmGUI\favorites.conf
05:09:33 : Error reading favorites.conf
05:09:33 : Waiting for device in RCM mode
05:09:33 : Add favorites to listbox
05:09:34 : Waiting for device in RCM mode
05:09:40 : File doesn't exist`

I found the origin of the issue.

Drive O:\ is a network share from a Synology NAS
If i move TegraRCMGUI folder to a local hard disk, favorites.conf is loaded.

**Comment by eliboa** [comment]
Thank you.
Strange, it should work though, it's working with my WD NAS (Samba3).
I'm gonna look into it.

**Comment by capitaineflam25** [comment]
The strange thing is that the conf file is created and written without any error.
If you'll need more tests don't hesitate.

**Comment by eliboa** [comment]
Merci ;) I'll let you know.

**Comment by jowadmax** [comment]
Maybe it's the non-standard characters in the file path?
Maybe change the 'é' characters to 'e' in the top root directory, test, and change them back.

**Comment by capitaineflam25** [comment]
That's as simple as that ! If move to a folder without any accentued char it's OK.
There must be something wrong in the file reading, that is OK with the file writing...

**Comment by eliboa** [comment]
Well I tried to reproduce this bug with both portable and installer version but it worked everytime I tried.
I tried with this path (among others)  : "C:\...\testé caract spéciôx\hékate_ctcaer_2.3.bin". It's hard to debug without being able to reproduce :-/

**Comment by capitaineflam25** [comment]
No problem. Once we know the origin of the issue we can work around.

**Comment by eliboa** [comment]
Hooray ! You were right jowadmax, I followed your method and I was able to reproduce 👍 
Now I can debug and find a solution, thank you. I wonder if the problem could come from the payload's path encoding (UTF8) ? I'll let you know. Thank you both.

**Comment by eliboa** [comment]
@capitaineflam25 do ou mind testing this binary https://drive.google.com/open?id=1A9UTnZCvMDbRqxHjSBVdAx5TX94dYb6D (just copy it in TegraRcmGUI -portable- directory)?
I think I fixed the problem, I removed UTF8 encoding for favorites.conf and presets.conf paths.
Thank you

**Comment by capitaineflam25** [comment]
You made it ! Bien joué 😋
Tested successfully with this binary

**Comment by eliboa** [comment]
😄  enfin ! merci pour ton aide.
The fix will be included in next release.
