### ISSUE TITLE
TegraRCMGUI stops responding when attempting to inject payload

### ISSUE THREAD

**Issue by nick97999** [eliboa/TegraRcmGUI#34]
Hello, please help me. I have been stuck on this for a while and have done a lot of research. Tegrarcmgui keeps freezing when I inject hekate_ctcaer_5.1.1 and it freezes after "Invoking TegraRcmSmash.exe with args". Some of the other threads said that I need a data transferable cable but how do I know which ones are data transferable. And some others said that it could be my PC, well how do I know. Please help!

**Comment by eliboa** [comment]
Not related to TegraRcmGUI.
Please try another payload launcher to test your cable, for example :  https://fusee-gelee.firebaseapp.com/
