### ISSUE TITLE
[Cosmetic] Image resolution adjustment

### ISSUE THREAD

**Issue by capitaineflam25** [eliboa/TegraRcmGUI#4]
Hi,

since 2.0, image container may have been resized resulting in a lower readability :

![image](https://user-images.githubusercontent.com/985702/41915090-1eda8f00-7955-11e8-845c-5705443cb8cc.png)

**Comment by eliboa** [comment]
Hi, 

Thanks for reporting this. I'm already working on a solution (it actually depends on your screen resolution). It'll be released with v2.1 (with other bug fixes) in a few days, hopefully ;)

**Comment by eliboa** [comment]
I made some change to improve readability for those bitmaps. I could have done better but i'm so lazy ^^
I guess the result will depend on your screen resolution but this should be better for low resolutions.
Check out [TegraRcmGUI_v2.1](https://github.com/eliboa/TegraRcmGUI/releases/tag/2.1)

**Comment by capitaineflam25** [comment]
That's perfect !
![image](https://user-images.githubusercontent.com/985702/42057197-e194d866-7b1c-11e8-8487-3025bad5f6dc.png)
