### ISSUE TITLE
Stuck on Uploading payload

### ISSUE THREAD

**Issue by DarkSmileee** [eliboa/TegraRcmGUI#41]
Hello,

I was trying to inject a payload but when ever I use the GUI it freezes and when I use the Smash it gets stuck on Uploading payload (mezzo size: 92, user size: 76328, total size: 142544, total padded size: 143360)...

If tried multiple cables nothing seems to help any idea? 
![Screenshot_1](https://user-images.githubusercontent.com/60740373/79047248-c0431280-7c15-11ea-85ea-13df5258e778.png)

**Comment by simpl-t0n** [comment]
Same here.

**Comment by DarkSmileee** [comment]
> Same here.

I found out I had this issues because my switch is XKJ serial number so I will have to wait
