### ISSUE TITLE
Error injecting = RC=-50

### ISSUE THREAD

**Issue by Yuberz** [eliboa/TegraRcmGUI#5]
What does this mean?

**Comment by Yuberz** [comment]
Welp, seems like restarting my computer and the .exe solved it. Never mind!

**Comment by GhostlyCrowd** [comment]
i randomly get this too

**Comment by eliboa** [comment]
RC -50 is triggered when the program fails to create a child process to run TegraRcmSmash.exe. I don't know why this is happening, maybe because a previous child is still active. I'm gonna look into it. Thank you both for reporting this.

**Comment by eliboa** [comment]
@santhoshr you were right.
This bug should be fixed now. Please let me know 😏

**Comment by FriendHealy** [comment]
I'm getting this error code just now and I know cant seem to turn my switch back on. I know pretty much nothing about computer code or the language, myself so any help in baby terms would be appreciated! It was working fine the other day and nothing has changed since then
