### ISSUE TITLE
Option to add TegraRcmSmash argument

### ISSUE THREAD

**Issue by ppkhoa** [eliboa/TegraRcmGUI#7]
Add option to include extra arguments when TegraRcmSmash is run, i.e. add -r for USB readback.

**Comment by eliboa** [comment]
Hello.
What for ? I mean, do you have a feature in mind ? Why not use TegraRcmSmash instead ?
TegraRcmGUI is for the end user, if you can think about something to use readback function for (like UMS Tool), please tell me and i'll look into it 😉

**Comment by ppkhoa** [comment]
Hi there, I was loading the biskeydump to grab the keys from the console, instead of grabbing a phone to scan the QR code and then find a way to copy the text to computer, the USB readback can be implemented in the GUI so the data can be copied and backed up somewhere without the need for a camera? Maybe this use case is too specific but the ability to specify certain options for the payload could be useful for end-user as well.

**Comment by eliboa** [comment]
Hi, sorry for the late answer. I didn't know that biskeydump payload uses the readback feature. Unfortunately I have no time to work on TegraRcmGUI right now but i'm gonna look into it as soons as i have some free time ^^.

**Comment by eliboa** [comment]
Partially implemented in v2.5
https://github.com/eliboa/TegraRcmGUI/releases/tag/2.5

**Comment by eliboa** [comment]
I will not go further to implement passing arguments to TegraRcmSmash
