### ISSUE TITLE
Use relative path for portable version

### ISSUE THREAD

**Issue by RedSparr0w** [eliboa/TegraRcmGUI#8]
Use relative paths for the portable release (when payload located on the same drive).

`../payloads/payload.bin`

**Comment by eliboa** [comment]
Added : use of relative path for favorites ([#2516e81](https://github.com/eliboa/TegraRcmGUI/commit/2516e8192daf3080586a479f911043273da9ceb1).
Todo : implement relative path for selected payload (presets)

**Comment by RedSparr0w** [comment]
Thanks!
👍
